name: "Run workflow"

on:
  # Schedule: At 15:00 UTC on every day of month:
  schedule:
    - cron: '0 15 * * *'

  # Enable manual run for this workflow:
  workflow_dispatch:

env:
  GDRIVE_API_CREDENTIALS: ${{ secrets.GDRIVE_API_CREDENTIALS }}

jobs:
  RUN:
    name: Scrape job
    runs-on: ubuntu-latest
    steps:
      # checkout repository
      - name: Checkout
        uses: actions/checkout@v2
      
      # Run scraper
      - name: Scraper
        run: |
          python python/scraper.py
