name: "Run workflow"

on:
  pull_request:
    branches: 
      - main


jobs:
  Info:
    name: Info job
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Print 
        run: |
          git status
          git diff